# Use the official OpenJDK 21 image from the Docker Hub
FROM openjdk:21

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY digitalstore.jar .

# Specify the command to run the JAR file
CMD ["java", "-jar", "digitalstore.jar"]
